spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ldt_booking
    username: role
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/ldt_booking
    user: role
  rsocket:
    server:
      port: 7003
server:
  port: 8093
