spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ldt_user
    username: role
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/ldt_user
    user: role
  rsocket:
    server:
      port: 7000
server:
  port: 8094
